// Mocks generated by Mockito 5.4.6 from annotations
// in poke_app/test/features/pokemons/pokemons_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i18;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:poke_app/src/common/enums/pokemons_enums.dart' as _i15;
import 'package:poke_app/src/common/results/result.dart' as _i6;
import 'package:poke_app/src/common/services/connection_service.dart' as _i2;
import 'package:poke_app/src/common/services/http_service.dart' as _i4;
import 'package:poke_app/src/common/states/state.dart' as _i17;
import 'package:poke_app/src/features/pokemons/data/data_sources/pokemons_data_source.dart'
    as _i5;
import 'package:poke_app/src/features/pokemons/data/models/pokemon_model.dart'
    as _i7;
import 'package:poke_app/src/features/pokemons/domain/entities/pokemon_entity.dart'
    as _i10;
import 'package:poke_app/src/features/pokemons/domain/use_cases/filter_by_type_use_case.dart'
    as _i9;
import 'package:poke_app/src/features/pokemons/domain/use_cases/get_all_pokemons_use_case.dart'
    as _i11;
import 'package:poke_app/src/features/pokemons/domain/use_cases/get_related_pokemons_use_case.dart'
    as _i12;
import 'package:poke_app/src/features/pokemons/domain/use_cases/search_pokemons_use_case.dart'
    as _i13;
import 'package:poke_app/src/features/pokemons/domain/use_cases/sort_pokemons_use_case.dart'
    as _i14;
import 'package:poke_app/src/features/pokemons/presentation/view_models/pokemons_view_model.dart'
    as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i2.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> checkConnection() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnection, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpService extends _i1.Mock implements _i4.HttpService {
  MockHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<({dynamic data, String? error, int? statusCode})> getData({
    required String? path,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [], {#path: path}),
            returnValue:
                _i3.Future<
                  ({dynamic data, String? error, int? statusCode})
                >.value((data: null, error: null, statusCode: null)),
          )
          as _i3.Future<({dynamic data, String? error, int? statusCode})>);
}

/// A class which mocks [PokemonsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonsDataSource extends _i1.Mock
    implements _i5.PokemonsDataSource {
  MockPokemonsDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<List<_i7.PokemonModel>, Exception>> getAllPokemon() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPokemon, []),
            returnValue:
                _i3.Future<_i6.Result<List<_i7.PokemonModel>, Exception>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.PokemonModel>, Exception>>(
                    this,
                    Invocation.method(#getAllPokemon, []),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<List<_i7.PokemonModel>, Exception>>);
}

/// A class which mocks [FilterByTypeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilterByTypeUseCase extends _i1.Mock
    implements _i9.FilterByTypeUseCase {
  MockFilterByTypeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.PokemonEntity> call(
    List<_i10.PokemonEntity>? pokemonList,
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [pokemonList, type]),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);
}

/// A class which mocks [GetAllPokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPokemonsUseCase extends _i1.Mock
    implements _i11.GetAllPokemonsUseCase {
  MockGetAllPokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Result<List<_i10.PokemonEntity>, Exception>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<
                  _i6.Result<List<_i10.PokemonEntity>, Exception>
                >.value(
                  _i8.dummyValue<
                    _i6.Result<List<_i10.PokemonEntity>, Exception>
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i3.Future<_i6.Result<List<_i10.PokemonEntity>, Exception>>);
}

/// A class which mocks [GetRelatedPokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRelatedPokemonsUseCase extends _i1.Mock
    implements _i12.GetRelatedPokemonsUseCase {
  MockGetRelatedPokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.PokemonEntity> call(
    _i10.PokemonEntity? pokemon,
    List<_i10.PokemonEntity>? allPokemon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [pokemon, allPokemon]),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);
}

/// A class which mocks [SearchPokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchPokemonsUseCase extends _i1.Mock
    implements _i13.SearchPokemonsUseCase {
  MockSearchPokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.PokemonEntity> call(
    List<_i10.PokemonEntity>? pokemonList,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [pokemonList, query]),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);
}

/// A class which mocks [SortPokemonsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSortPokemonsUseCase extends _i1.Mock
    implements _i14.SortPokemonsUseCase {
  MockSortPokemonsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.PokemonEntity> call(
    List<_i10.PokemonEntity>? pokemonList,
    _i15.SortType? sortType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [pokemonList, sortType]),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);
}

/// A class which mocks [PokemonsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonsViewModel extends _i1.Mock implements _i16.PokemonsViewModel {
  MockPokemonsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.AppState<List<_i10.PokemonEntity>> get pokemonState =>
      (super.noSuchMethod(
            Invocation.getter(#pokemonState),
            returnValue: _i8
                .dummyValue<_i17.AppState<List<_i10.PokemonEntity>>>(
                  this,
                  Invocation.getter(#pokemonState),
                ),
          )
          as _i17.AppState<List<_i10.PokemonEntity>>);

  @override
  List<_i10.PokemonEntity> get displayedPokemon =>
      (super.noSuchMethod(
            Invocation.getter(#displayedPokemon),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);

  @override
  _i15.SortType get currentSort =>
      (super.noSuchMethod(
            Invocation.getter(#currentSort),
            returnValue: _i15.SortType.alphabetical,
          )
          as _i15.SortType);

  @override
  List<String> get availableTypes =>
      (super.noSuchMethod(
            Invocation.getter(#availableTypes),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> loadPokemon() =>
      (super.noSuchMethod(
            Invocation.method(#loadPokemon, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void searchPokemon(String? query) => super.noSuchMethod(
    Invocation.method(#searchPokemon, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void sortPokemon(_i15.SortType? sortType) => super.noSuchMethod(
    Invocation.method(#sortPokemon, [sortType]),
    returnValueForMissingStub: null,
  );

  @override
  void filterByType(String? type) => super.noSuchMethod(
    Invocation.method(#filterByType, [type]),
    returnValueForMissingStub: null,
  );

  @override
  void clearFilters() => super.noSuchMethod(
    Invocation.method(#clearFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i10.PokemonEntity> getRelatedPokemon(_i10.PokemonEntity? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#getRelatedPokemon, [pokemon]),
            returnValue: <_i10.PokemonEntity>[],
          )
          as List<_i10.PokemonEntity>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
